### ISSUE TITLE
Branch bash-4.4 missing

### ISSUE THREAD

**Issue by jansorg** [Trepan-Debuggers/bashdb#1]
Is GitHub the new, official home of bashdb now?
I'd appreciate it 😀 

The branch bash-4.4 is on SF but not yet here on GitHub.
Unless that's intentional, I'd copy it to here, too.

**Comment by rocky** [comment]
> Is GitHub the new, official home of bashdb now? I'd appreciate it 😀

We in the process of transitioning. I'll still copy releases to sourceforge and we can have the issues and discussions. But as for git commits let's please use github. 

I do appreciate the service that sourceforge has provided over the years, especially before github existed.


> 
> The branch bash-4.4 is on SF but not yet here on GitHub. Unless that's intentional, I'd copy it to here, too.

Branch pushed now.

**Comment by jansorg** [comment]
> We in the process of transitioning. I'll still copy releases to sourceforge and we can have the issues and discussions. But as for git commits let's please use github. 

Okay. I'll submit PRs here, but will submit issues at SourceForge.

> I do appreciate the service that sourceforge has provided over the years, especially before github existed.

I still remember the early days with SourceForge and CVS 🙂 I'm also grateful for its service, especially when nothing comparable was available for open-source software...

> Branch pushed now.

Thanks! In the next few days, I'll move over my change requests from SF.net to here.
