### ISSUE TITLE
Absolute breakpoint not when it appears as a relative path that has changed cwd from the time it was set

### ISSUE THREAD

**Issue by rocky** [Trepan-Debuggers/bashdb#55]
This is the second bug mentioned in https://github.com/Trepan-Debuggers/bashdb/issues/50

1. bashdb is launched from a directory, which is not the parent of `main.bash` and `lib.bash`
2. Running the bashdb commands below which changes cwd, the script just ends without hitting the breakpoint in `lib.bash`

I think it's not hit because none of the candidates to resolve a relative path (`./lib.bash`) is the right one. AFAIK it's searching in the initial working dir and current working dir of the script.

I think it may be possible to fix this if the paths to `source` could be recorded as absolute paths.
But I'm not sure if that's even possible.

## Test Case
File `main.bash`:

```bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

. ./lib.bash # if this is changed into ". $DIR/lib.bash", then the breakpoint is hit
cd "$HOME"
libFunction world
```

File `lib.bash`:
```bash
libFunction() {
    echo hello "$1" # <--- breakpoint on this line
}
```

bashdb session:
```text
# ./bashdb -L . /path/to/main.bash
load /path/to/lib.bash
break /path/to/lib.bash:1
cont
info stack
```

**Comment by jansorg** [comment]
I think this issue was fixed by https://github.com/Trepan-Debuggers/bashdb/pull/54?

**Comment by rocky** [comment]
I just checked, and yes it is.
